# Code to get the names and locations of the stations in
#  4.6.1 but not in v3

import pandas
import os

bindir = os.path.abspath(os.path.dirname(__file__))
nsfile = "%s/new_stations" % bindir


def get_new_stations():

    o = pandas.read_fwf(
        nsfile,
        colspecs=[
            (0, 19),
            (20, 50),
            (52, 64),
            (66, 68),
            (69, 72),
            (74, 80),
            (81, 87),
            (88, 95),
            (97, 102),
            (103, 110),
            (111, 112),
            (113, 123),
            (124, 134),
            (135, 145),
            (146, 156),
            (157, 167),
            (168, 175),
            (176, 183),
            (184, 191),
            (192, 200),
            (201, 205),
            (206, 213),
            (214, 221),
            (222, 223),
        ],
        header=None,
        encoding="ISO-8859-1",
        names=[
            "UID",
            "Name",
            "ID",
            "Type",
            "NCEP.Type",
            "Longitude",
            "Latitude",
            "Observed",
            "Time.offset",
            "Observed.2",
            "Skipped",
            "Bias.correction",
            "Obfit.prior",
            "Obfit.post",
            "Obsprd.prior",
            "Obsprd.post",
            "Oberrvar.orig.out",
            "Oberrvar.out",
            "Oberrvar.use",
            "Paoverpb.save",
            "Prob.gross.error",
            "Localization.length.scale",
            "Lnsigl",
            "QC.failure.flag",
        ],
        converters={
            "UID": str,
            "Name": str,
            "ID": str,
            "Type": str,
            "NCEP.Type": int,
            "Longitude": float,
            "Latitude": float,
            "Observed": float,
            "Time.offset": float,
            "Observed.2": float,
            "Skipped": int,
            "Bias.correction": float,
            "Obfit.prior": float,
            "Obfit.post": float,
            "Obsprd.prior": float,
            "Obsprd.post": float,
            "Oberrvar.orig.out": float,
            "Oberrvar.out": float,
            "Oberrvar.use": float,
            "Paoverpb.save": float,
            "Prob.gross.error": float,
            "Localization.length.scale": float,
            "Lnsigl": float,
            "QC.failure.flag": int,
        },
        na_values=[
            "NA",
            "*",
            "***",
            "*****",
            "*******",
            "**********",
            "-99",
            "9999",
            "-999",
            "9999.99",
            "10000.0",
            "-9.99",
            "999999999999",
            "9",
        ],
        comment=None,
        compression="infer",
    )
    return o
